### ISSUE TITLE
Laravel 7 compatibility 

### ISSUE THREAD

**Issue by SeinopSys** [valorin/pwned-validator#10]
I'd like to ask for an update to this package for Laravel 7

**Comment by mralston** [comment]
The package works in Laravel 7, it just won't install using composer because the new version of illuminate/support needs updating in the package's composer.json file.

I've just downloaded the package from the GitHub repo, saved it to a folder called vendor_static and manually added to the PSR-4 autoload section using:

```
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Valorin\\Pwned\\": "vendor_static/pwned-validator/src/"
        },
```

For some reason the validation rule wasn't found using the string name, so I had to use the class instead. I'm assuming this is something to do with the way I've imported the package, rather than a problem with the package itself.

```
'password' => ['nullable', 'string', 'min:8', 'dumbpwd' , new \Valorin\Pwned\Pwned]
```

Other than that, it seems to work just fine in Laravel 7.

**Comment by valorin** [comment]
I was going to check on it this afternoon, but I see a PR is already waiting for me. Thanks @mralston! 😁 
I'll go ahead and approve and tag that right now. So you should be able to pull it into composer shortly.

**Comment by valorin** [comment]
v1.3.2 should be live now 👍

**Comment by mralston** [comment]
Nice. My first contribution to the open source community. 😊

- Matt

**Comment by valorin** [comment]
That is awesome! 😃
